### ISSUE TITLE
name

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#1]
wafflejs is a solid placeholder name. @billyroh suggested it because, "everyone likes waffles, right?" we're open to others and can deal with migrating the org and repo elsewhere.

**Comment by visnup** [comment]
@janekimmer suggested cocojs. I'm of course partial, but like wafflejs too. all of a sudden the existing Coco stickers in the wild take on a new meaning though, which is kinda cool. but then again, I like how Coco just has her own brand.

**Comment by llkats** [comment]
I like WaffleJS quite a bit -- there's a bit of a food/beverage theme here in the Bay Area, with SushiJS, BeerJS, and PoutineJS!

Two suggestions that jumped to mind are SutroJS and BaeJS, but I'm not sure if either come close to WaffleJS. :smile:

**Comment by visnup** [comment]
awesome, glad you like it. BaeJS is pretty clever and cute. and yeah I never thought about the food theme we do have going on around here. now I'm hungry.

**Comment by visnup** [comment]
going to say we're going with wafflejs. it's been a whole 4 days and I registered so many accounts now. :stuck_out_tongue: calling this done.
