### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#10]

**Comment by makenai** [comment]
![waffle](https://cloud.githubusercontent.com/assets/11425/8273888/49399ba8-1835-11e5-8e40-af36d13cce13.png)

Just to put something here.

**Comment by visnup** [comment]
hahaha. that's actually pretty clever. I'm watching billy placing whipped butter on an 8-bit waffle as we speak though.

**Comment by visnup** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/10444/8273973/93344476-1838-11e5-90d4-88f8e7741e74.jpg)

**Comment by visnup** [comment]
@makenai I really like that idea

**Comment by billyroh** [comment]
:strawberry: ![artboard 1 copy](https://cloud.githubusercontent.com/assets/748504/8315877/5f9a2678-19a8-11e5-8d86-b1a702551d8b.png)

**Comment by visnup** [comment]
@billyroh we should use stickers as drink tickets

**Comment by visnup** [comment]
![waffle js ideas](https://cloud.githubusercontent.com/assets/10444/8322514/4ae14b1a-19eb-11e5-82db-713f973afa06.png)
