### ISSUE TITLE
CircleCI is spamming the master branch

### ISSUE THREAD

**Issue by timhudson** [wafflejs/wafflejs.github.io#100]
CircleCI has been spamming the master branch with commits since 28dc579edb6d827ff966a13315682ebb399a3299 reverted 83be482e5a73dd27fef1dcf2490806cb9cb435b6. The CI deployment config seems to listen on master for changes which then creates a new commit on master which then... you get the idea.

**Comment by visnup** [comment]
Crap. Thought I fixed this but never double checked. Fixing. Thanks for reporting!

**Comment by visnup** [comment]
fixed.

@billyroh going to do some surgery on all the master branch. force push incoming.
