### ISSUE TITLE
Google calendar?

### ISSUE THREAD

**Issue by DTrejo** [wafflejs/wafflejs.github.io#123]
Just curious is there a google calendar I can subscribe to so I know when wafflejs is coming up?

Maybe I missed it on the site?

Thanks and great work, last time I went it was awesome :) !
David

**Comment by visnup** [comment]
would something like http://cl.ly/eZrU/download/WaffleJS.ics work?

**Comment by DTrejo** [comment]
Thank you! That worked great (hopefully google calendar is smart enough to
add new events as you add them, I don't know how ics works).

Cheers & cya soon I hope!
D
