### ISSUE TITLE
Call for Announcements: March

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#131]
![Announcements](http://i.giphy.com/3o85xtWMj6Hbv1PakE.gif)

If you have an announcement of an event or similar, please add it to this list and we'll consolidate to announce during the beginning of wafflejs. Things similar to the existing list below. No purely-sponsor things, please. If you're attending and want to give a ~5-10 second shoutout, please let us know too.

- JSConf Iceland -- Aug 25-26 (@kristjanmik)
  - Tickets on sale
  - Call for speakers (due Mar 31)
- NodeConf Adventure -- Jun 9-12 (@mikeal)
  - Tickets on sale
- NodeSchool SF -- Mar 26 1 - 5 PM (@jedireza @llkats)
- NodeSchool Oakland (@Fauntleroy)
- EmberConf Portland -- Mar 28-30
  - @visnup is going
- SFNode -- Mar 3 6:30 - 9 PM (@dshaw)
  - Blizzard (Market and 7th)

**Comment by visnup** [comment]
@dshaw announcement for SFNode tomorrow?

**Comment by Fauntleroy** [comment]
Will there be slides? Can the nodeschool one have:

- nodeschool.io/sanfrancisco
- nodeschool.io/oakland
- @nodeschoolsf
- @nodeschooloak

**Comment by jedireza** [comment]
NodeSchool Oakland is teaming up with NodeSchool SF on March 26th from 1pm - 5pm at Mozilla SF.

We have a full set of mentors already but are always looking to include mentors from underrepresented groups (this month our gender diversity could be better). Please contact us if you're interested.

 - The address is: 2 Harrison St, San Francisco, CA 94105
 - Registration link: https://ti.to/nodeschoolsf/march-26th-2016
 - Mentor registration: https://github.com/nodeschool/sanfrancisco/issues/123

If we're able to get information on a slide:

 - NodeSchool SF logo http://nodeschool.io/sanfrancisco/assets/logo.png
 - NodeSchool OAK logo http://nodeschool.io/oakland/images/nodeschool_oak.png
 - Twitters @nodeschoolsf @nodeschooloak

**Comment by visnup** [comment]
@jedireza it's basically one line of a slide. I can fit in date, address, and twitter handles. and let either of you talk to the rest.

**Comment by jedireza** [comment]
:+1: cool thanks

**Comment by llkats** [comment]
Represent us well, @jedireza and @Fauntleroy!! :dancers:
