### ISSUE TITLE
Call for Announcements: April

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#140]
![Announcements](http://i.giphy.com/Fuf40rhHUVDhK.gif)

If you have an announcement of an event or similar, please add it to this list and we'll consolidate to announce during the beginning of wafflejs. Things similar to the existing list below. No purely-sponsor things, please. If you're attending and want to give a ~5-10 second shoutout, please let us know too.

- JSConf Iceland -- Aug 25-26 (@kristjanmik)
  - Tickets on sale
  - Call for speakers (due Mar 31)
- NodeConf Adventure -- Jun 9-12 (@mikeal)
  - Tickets on sale
- NodeSchool SF and Oakland (@Fauntleroy @jedireza @llkats)

**Comment by Fauntleroy** [comment]
@jedireza @llkats come announce with me!

**Comment by jedireza** [comment]
@Fauntleroy great idea. I have to make sure I'm in town, if so, I'll be there :+1:

**Comment by Fauntleroy** [comment]
The next NodeSchool Oakland is on April 16th from 1-5PM at npm: https://ti.to/nodeschool-oakland/nodeschool-oakland-april-npm

**Comment by jedireza** [comment]
The next NodeSchool SF is on April 30th from 1-5PM at Mozilla SF: https://ti.to/nodeschoolsf/april-30th-2016

**Comment by visnup** [comment]
@Fauntleroy @jedireza added.
