### ISSUE TITLE
Charity

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#15]
Which Bay Area charity should we donate to? Here are some ideas:
* http://www.blackgirlscode.com/
* http://www.missiongraduates.org/

Not sure if we want to make it tech-related or not.

**Comment by visnup** [comment]
I would've assumed tech related

**Comment by billyroh** [comment]
@visnup Girls Who Code also seems pretty good. They spend ~80% of their funds on programs: http://girlswhocode.com/2014report/

**Comment by billyroh** [comment]
Visnu and I discussed it irl and we're going with Girls Who Code!

**Comment by visnup** [comment]
if anyone has more suggestions, just let us know.
