### ISSUE TITLE
August Call for Speakers

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#16]
We're looking for speakers for our meetup!

![mind blown](http://i.giphy.com/EldfH1VJdbrwY.gif)

**How do I submit a talk?**
You can either comment on this issue or [send us an email](mailto:talks@wafflejs.com?subject=Talk Submission).

**What should I talk about?**
Something you do outside of work. It doesn't have to be tech-related, but it'd be nice!

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
Just a few sentences describing what you want to talk about would be great.

**What's the A/V situation?**
We'll have a TV and a mic for you to use. Let us know if you need any fancy adapters (we'll have some Apple ones).

**Comment by visnup** [comment]
@contra do you have a summary of what you want to talk about? are you around for August 5? http://wafflejs.com

**Comment by contra** [comment]
@visnup um i have a few things but id like to do a short lightning talk about an experiment i did with automated lobbying using mechanical turk and taskrabbit to get the city of SF to change some light bulbs

**Comment by visnup** [comment]
@contra hah, I like it. are you free August 5?

**Comment by contra** [comment]
@visnup Yeah most likely, feel free to put me in the schedule if you want. Talk title will be "Experiments in Automated Lobbying"

**Comment by visnup** [comment]
@contra awesome. going to add you. sent you a ticket too.

**Comment by nebrius** [comment]
I gave a talk last week about tips for successfully hacking in your spare time w/o it taking over your life. I could definitely fit this into 10 minutes, if meta talks are your thing :)

**Comment by TheAlphaNerd** [comment]
I would be up for given a 10 minute version of my Cascadia talk

I would title it

"OMFG Node File Watchers, are you forrrreeeeaaaall?"

**Comment by visnup** [comment]
@nebrius @TheAlphaNerd both sound interesting. give us a week to try to round a few more.

**Comment by jingidy** [comment]
I would love to talk about life in the Indonesian slums. My visit there changed my perspective on what is rich, what is poor, what is happiness, and what is importance... which changed the lens I evaluate tech communities by.

**Comment by visnup** [comment]
@jingidy that sounds super interesting (at least to me). now I want, like, 6 talks in a night.

**Comment by jeanieshark** [comment]
I'd be down to talk in September about diversity issues in tech/how to foster discussions about them!

**Comment by keenahn** [comment]
Are you still looking for another talk for Aug 5?

**Comment by visnup** [comment]
@keenahn we're trying to pick our last one by Monday Jul 13, so if you have a proposal, sure! otherwise, just opened a September Call for Speakers (#34).

**Comment by billyroh** [comment]
Thanks everyone for submitting your talks! We've announced our speakers over here: http://wafflejs.com/

If you'd like to speak for our September event, we're accepting talks over here: https://github.com/wafflejs/wafflejs.github.io/issues/34
