### ISSUE TITLE
Audio equipment

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#19]
Going to need I think:

- [ ] mixing board
- [ ] more microphones
- [ ] cables
- [ ] projector
- [ ] projector screen

**Comment by visnup** [comment]
@mikeal how sophisticated is your audio setup? Should we just rent?

**Comment by visnup** [comment]
@thealphanerd?

**Comment by TheAlphaNerd** [comment]
If I recall @mikeal was pretty stoked about having the gear in his place and it not moving for a minute.

Where are you thinking of holding this event. Some venues (such as Mikeal's or github) have a bunch of equipment we could already use.

**Comment by TheAlphaNerd** [comment]
I took a look at the page and noticed the meetup is to happen at SOMA Streateats... I know they have speakers in the main sitting area. They may have the majority of gear needed. Alternatively I think we can get mixer + mics + cables for like 100 bucks or something. A cheap 2nd hand mixer can probably be sourced from craigslist fairly easily.

**Comment by visnup** [comment]
we found a rental that specializes in a karaoke setup for $240. I'm just hesitant to be fully dependent on them for all of the audio. mostly I'm just worried about a late/tardy setup setting everything back and causing undue stress. so, the more we either have on hand or know how to setup ourselves, the better I'll feel.

![pasted_image_at_2015_06_29_10_42_am_360](https://cloud.githubusercontent.com/assets/10444/8438059/5231b878-1f18-11e5-809e-1176981af560.png)

**Comment by visnup** [comment]
soma street food has a mic and a speaker and a TV. I think it's all wired directly together too. they explicitly said they don't have a mixing board.

**Comment by TheAlphaNerd** [comment]
https://sfbay.craigslist.org/nby/msg/5095846060.html

$100

**Comment by visnup** [comment]
aw man, if I buy this I can feel like I'm becoming @mikeal.

**Comment by TheAlphaNerd** [comment]
fwiw... I don't know if that is the exact mixer to get... @othiym23 might have a better opinion. I more wanted to show how affordable buying some of this gear can be:D

**Comment by visnup** [comment]
haha. I'm more now just looking for a hobbyist "sound techie". I'm cool buying base gear. it's nice and reproducible each month.

@TheAlphaNerd know of a talented guitarist? I'm looking for someone who can do a few live accompaniments on acoustic. or maybe @emilyrose, could Natasha do accompaniment for some karaoke-ish songs?

**Comment by billyroh** [comment]
On top of a mixer, we'll need to get some mics too. They're not cheap, but they're a one-time cost. https://sfbay.craigslist.org/search/sfc/msa?query=wireless+microphone

**Comment by TheAlphaNerd** [comment]
@visnup I play guitar... and have a stage acoustic... havn't played in a minute but if it is basic chords I could probs make it happen. I also know a handful of other talented musicians I could call on

**Comment by mikeal** [comment]
Most of my audio setup is still shut down after NodeConf.

If they have speakers and amps and all you need is the mixer and mics it's easy enough to load in and out.

**Comment by visnup** [comment]
@TheAlphaNerd want to meet up with me and do a dry-run rehearsal to see if we're both up for it (I'm thinking of opening with a song)??

@mikeal thinking about just buying the same equipment. any recommendations? if we get really lazy then we might switch to borrow-mode.

**Comment by TheAlphaNerd** [comment]
@visnup definitely into it... we should cross co-ordinate it with food... I like food.

I won't really be able to give it time until after I get back from cascadia though... 12th of July

**Comment by visnup** [comment]
ok, will schedule with you outside of here (twitter).

**Comment by mikeal** [comment]
@visnup this is the mixer I have http://www.amazon.com/dp/B00352MHGA/?tag=httpwwwfutu0b-20

I have pretty expensive headset mics (about 300 a piece) from countryman. But, the most important thing to try and keep compatible is the wireless packs. Both @voodootikiod and I use the Shure system http://www.amazon.com/dp/B00IVPFVSM/?tag=httpwwwfutu0b-20

**Comment by visnup** [comment]
@mikeal awesome, thanks for the tips.

**Comment by visnup** [comment]
@mikeal can we borrow your projector screen (the one I've setup so many times 😉)?

**Comment by visnup** [comment]
@emilyrose has most of the equipment we need. Doing a dry run with it next week. Going to call this issue closed.

**Comment by mikeal** [comment]
@visnup you can but you'll have to go to Oakland to get it. I can give you the key but I'll be pretty slammed with FooCamp and the Collaborator Summit back-to-back that week so I won't be able to go grab it myself, I'm just hoping I have enough time to attend :)

**Comment by emilyrose** [comment]
@mikeal @visnup I'm happy to pick it up since I will most likely be closer to Oakland if it's helpful :smile:

**Comment by mikeal** [comment]
@emilyrose are you gonna be in the city somewhere i can meet you to give you the key tho?

**Comment by emilyrose** [comment]
@mikeal maybe not!

**Comment by visnup** [comment]
@mikeal @emilyrose I can figure out a time to go get it when I get back into town Monday. I'll just come to you to get the key and then go grab it.
