### ISSUE TITLE
vegan waffles?

### ISSUE THREAD

**Issue by annthurium** [wafflejs/wafflejs.github.io#197]
Hi,

I just got tickets for myself and @deleted for October.  I'm vegan and he can't eat dairy.  Is there a way we can have vegan waffles?  I'd be happy to bring my own batter and waffle iron and do it DIY style, but wasn't sure if the venue allowed that.

Thanks, and I'm excited to check out the event either way!

cheers
Tilde

**Comment by visnup** [comment]
we should try to make this happen more regularly.

**Comment by billyroh** [comment]
Just sent an email to the vendor! I'll let you know once we get a response 😄

**Comment by billyroh** [comment]
Just heard back from the venue:
* Our vendor (nor any other vendor at the venue) sells vegan waffles.
* But! They're okay with us bringing in us own vegan waffle batter and waffle iron, which Visnu can bring.

Do you have a preference on either the vegan batter or toppings? We'll try to accommodate you as best as possible 😄

**Comment by kuychaco** [comment]
Any chance your waffle batter is gluten-free too @annthurium? 

Thanks so much for asking about this Tilde :). I'm allergic to gluten, dairy, and eggs and I've just been silently envying the waffle-eaters, as it didn't occur to me that this might be an option!

**Comment by annthurium** [comment]
@billyroh thank you so much!! <3 I really, really appreciate it.  I don't have a preference, really, as long as it's vegan!  

@kuychaco: I think I have a gf / vegan waffle batter recipe!  Lemmesee if I can dig it up...

**Comment by billyroh** [comment]
@annthurium: Just to circle back, we'll be going with this recipe: http://minimalistbaker.com/7-ingredient-vegan-gluten-free-waffles. It's both vegan and gluten-free!

Let us know if that doesn't work for you 😄

**Comment by annthurium** [comment]
Sounds great!
