### ISSUE TITLE
venue

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#2]
## criteria for a decision

- engenders creativity
  - non-corporate (no grand lobbies and elevators, no NDAs, no security guards with sign in sheets): this rules out most start-ups and co-working spaces.
  - hopefully not alcohol-first (read: straight up bar), but could be bar + open space or bar + art gallery, and really not too finicky on that point.
    - "i think alcohol is fine. the trick is to find somewhere with beer that's good and therefore expensive enough to promote moderation."
- can be reserved consistently every month on the same weekday for the near- to medium-term
- in SF (Oakland venue discussion in #11)
- easy to reach by public transit (for anyone coming from east bay)
- can hold ~90 semi-comfortably (only planning on 50 for the inaugural event)

## possibilities to contact

- [x] [SOMA Streatfood](http://www.somastreatfoodpark.com/reservations-1)
  - Bus holds 50. Barn holds 200.
- [x] [Electric Works](https://sfelectricworks.com)
  - @visnup knows the owner
- [x] 111 Minna
- [x] Public Works
- [x] Exploratorium
  - probably too big honestly, but maybe a single room would work?
- [x] Phoenix hotel
- [x] galette 88
- [ ] [Techshop](http://www.techshop.ws/Events.html)
- [ ] [New Mission Theater](http://drafthouse.com/san_francisco/new_mission)
- [ ] DNA Lounge

@visnup will call through this list and add notes as I go.

**Comment by visnup** [comment]
111 Minna? Or similar art galleries?

**Comment by visnup** [comment]
Public Works

**Comment by makenai** [comment]
Some random thoughts:

- I know it's in Oakland, but JSFest had some nice venues including The New Parkway Theater

- It would be a very different vibe, but the Phoenix hotel has an interesting 1960's feel - would be interesting - pool.js?

- The Exploratorium

**Comment by visnup** [comment]
@makenai oooh, exploratorium would be AMAZING (albeit way large). and I definitely want to try to bridge the divide between east and west here (see #5 and #6).

I want to try to keep to @jedschmidt's advice on picking a regular place, but I could see picking an SF and a Oakland venue and trying to do both. could be over-reaching though. of course, someone could come out of the woodworks and want to do the Oakland one better too.

**Comment by makenai** [comment]
Anything around Embarcadero station would be good then, eh? I wonder if there's anything workable inside / around the Ferry Building? I also popped open the map and saw this:

http://www.autodesk.com/gallery/design-nights

Never been there, but looks interesting. Autodesk is a little corporate, but I think this specific place tends a bit more toward a museum / public space.

**Comment by visnup** [comment]
[Galette88](http://www.galettesf.com/private-events.html) https://twitter.com/bysusanlin/status/612660670996197376

**Comment by visnup** [comment]
Re: Autodesk, yeah I'm not too excited about even a corporate name in the venue :stuck_out_tongue: 

around the ferry building area definitely is good. the more genuine and creativity-inspiring the better too.

**Comment by visnup** [comment]
@makenai thanks for all the suggestions by the way!

**Comment by visnup** [comment]
@ebryn suggested contacting [CODAME](http://www.codame.com/about/) too

**Comment by mikeal** [comment]
I have a warehouse in Oakland that can be used.

**Comment by kosamari** [comment]
here is few things we (or at least I) love about our BrooklynJS regular venue - 61Local
- good beer selections (seems to be a key)
- good non-alcoholic beverages (artisanal soda, konbuhca, tea, coffee - as non drinker myself really nice to have choice other than cheap soda from soda guns)
- dedicated space for talks (2nd floor holds ~ 90 ppl or so? after the event we can all head down to the bar or stay upstairs for more intimate chat)
- No ID check at the door (I assume it operates as a restaurant, not a bar?) (this was one down side of our June event venue :( we had to say no to few regulars under 21)

Hope it helps :) !

**Comment by mikeal** [comment]
Oh, this is my neighbor at the warehouse, they are open to doing a "tasting" at the right event -- for free. http://www.yelp.com/biz/irish-monkey-oakland

**Comment by llkats** [comment]
SOMA Streatfood actually works for a lot of @kosamari's points - generally good beer selection (great happy hour!), good non-alcoholic beverage selection, great variety of food, and open to minors. Downsides are that it can get a little chilly in the evening, but if we could rent out the barn, it'd be perfect.

Lost and Found is a staple for OaklandJS, though I don't think it really has a dedicated space for speaking.

The JS Everywhere conference was held in The Winery SF on Treasure Island, which was kinda fun! (But a little difficult to get to for pretty much everyone without shuttles.) http://sfeventvenues.com/index.php/san-francisco-event-venues/the-winery-sf

111 Minna looks really cool, and maybe this place could be a thing, though I can't speak for either from experience. http://969market.com/

Excited to see where WaffleJS goes!

**Comment by mikeal** [comment]
> Lost and Found

Great for informal stuff but can't really do talks (we looked in to it).

> The Winery SF on Treasure Island

Beautiful and pretty huge but quite expensive.

> 111 Minna

I looked in to it years ago, it's fairly small and quite expensive as well.

> The New Parkway

Beautiful space, super funky, and relatively cheap: http://www.thenewparkway.com/wp/wp-content/themes/new_parkway_theme/rental/Rental_Rates.Corporate.pdf

An evening event is $500-$600 an hour depending on the day. They have a beer/wine bar and food that has no minimum and you can just let the attendees have at it at their own expense. I suggest bringing your own mixer, mics, and podium though (I have all of these).

If we are planning on doing these regularly and we hit a good amount of food and beverage sales we can probably negotiate a better rental rate as well.

BTW, all of these venues require that you get an insurance rider for the event. I have business insurance that can do this pretty easily but it can cost up to $200 per event.

**Comment by mikeal** [comment]
Oh ya, the capacity in my warehouse is less than a hundred. Capacity in the awesome room at The New Parkway is 125.

**Comment by llkats** [comment]
The New Parkway was so awesome. Definitely +1 to that.

@mikeal is your warehouse the same one we went to for the last DanceJS? It's a great space, but a little tough to get to via BART -- I'm a little biased in favor of public transit ease.

**Comment by visnup** [comment]
I would probably nix @mikeal's warehouse based on public transit woes.

I think the favorite version of the future I foresee is one where we have 2 regular places, one in SF and one in Oakland, both easily accessible from transit and we figure out a way to bounce back and forth between the two at a regular interval. and then also punctuated with the ferry/Bart/shuttle idea.

what do people think about repeating an agenda?? like, two back to back events one in SF and one in Oakland with the same content (can you tell by the way that I'm throwing all logistical sanity to the wind right now)? I'm hoping the innate creativity of the events would result in two similar, but totally different events.

**Comment by mikeal** [comment]
Ya, the warehouse is not a good commute from Bart, but if you were doing that whole shuttle idea it wouldn't really matter :)

**Comment by mikeal** [comment]
Doing two events in two cities seems like a lot for an initial "let's get this off the ground" event. Also, splitting it between the cities and doing the same agenda means you lose the people who come over the bridge and segment the community a bit.

Do we have any sense of budget or ideas about how to raise the money?

**Comment by visnup** [comment]
agreed, going to concentrate on a first couple of events in SF first. will split Oakland venues and ideas out to another issue (#11).

the regular formula of sponsorships I'm fine going with for now. I can probably convince Opendoor to sponsor the first one ($500?). I think the main first cost is just venue and let attendees pay the bar themselves. we'll graduate to providing drink tickets at some point, but not now.

**Comment by philduffy** [comment]
One thing I think that's been extremely import to BrooklynJS is consistency. We are in the same venue every month (#20 was the first time we were not in 61Local), we are on the third Thursday of every month, we never skip a month, our tickets go on sale in two batches (2 Fridays before the event at 10am and the Friday before the event at 10am).

Not sure how that translates to SF / Oakland but I will point out that when BrooklynJS started it was the only BoroJS meetup. It's a pain to get to if you live in Queens (trust me, I live there).

**Comment by visnup** [comment]
@philduffy I fully agree with the consistency idea. I feel like it's also the only way to stay sane too.

**Comment by visnup** [comment]
[Techshop](http://www.techshop.ws/Events.html) was suggested

**Comment by mikeal** [comment]
> consistency. We are in the same venue every month

That's another mark against using the warehouse, I doubt I'll keep it after the end of the year.

> TechShop

I was a member of TechShop SF for a year. Unless they moved to a new space I don't see it being big enough to handle our crowd.

**Comment by mikeal** [comment]
You should reach out to the New Mission Theater. http://drafthouse.com/san_francisco/new_mission

It's owned by Alamo Drafthouse (where TXJS has been most years) and they definitely rent out for private events and have drink and food service.

**Comment by mikeal** [comment]
DNA is owned by jwz, old Netscape/Mozilla guy who cashed out and started this dance club ;)

**Comment by visnup** [comment]
yeah, it has nice dev cred. though, I don't use emacs. 😐

**Comment by makenai** [comment]
+1 to DNA Lounge. That would be a great venue if it's available. There are also musical acts, so it might be possible to coordinate with downstairs for an interlude?

**Comment by visnup** [comment]
just got prices for SOMA Streatfood. they are cheap. Mob-Wed, $75/hr for the bus (50 capacity) and $350/hr for the barn (200 capacity). we'd be starting out in the bus for ~2-3 hours so $225.

[ssfp_reservations_2015.pdf](https://github.com/wafflejs/wafflejs.github.io/files/242/ssfp_reservations_2015.pdf)

they're my top choice, so very likely going with them for 8/5.

**Comment by billyroh** [comment]
We're moving ahead with Streat Food! I'll close this out.
