### ISSUE TITLE
August Call for Karaoke Singers

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#21]
We're looking for people to sing karaoke at our meetup!

![I just wanna sing](http://38.media.tumblr.com/fc4adc9b136fda5aec00c4bbcb3e6775/tumblr_mysco2zJSc1qec814o1_500.gif)

**How do I submit a karaoke song?**
You can either comment on this issue or [send us an email](mailto:karaoke@wafflejs.com?subject=Karaoke Submission).

**What's this about?**
We want this meetup to be fun, so we're getting people to do karaoke between each speaker.

**How long should my song be?**
It should be <6 min long, so no Hotel California please!

**Do I need to be a good singer?**
Nope. You just need to be enthusiastic and [give us LIFE](https://ioneglobalgrind.files.wordpress.com/2014/05/yasss.gif?w=771&h=435).

**What should be in my karaoke submission?**
The song name and a link to the karaoke version of your song. We'll be using YouTube as a karaoke machine or we might try a live musical accompaniment.

**Comment by visnup** [comment]
nominating @isaacs.

**Comment by TheAlphaNerd** [comment]
nominating @potch

**Comment by ecin** [comment]
Will Smith - (Freakin' It)[https://www.youtube.com/watch?v=2zRII0IlPoE]

**Comment by makenai** [comment]
O-Zone - [Dragostea Din Tei](https://www.youtube.com/watch?v=WPCCAJILPj4)

**Comment by visnup** [comment]
@ecin I'm probably doing either an opening or closing one with @janekimmer. you should convince @daicoden to join in.

**Comment by visnup** [comment]
@rauchg any interest in singing? Or talking (#16)?

**Comment by visnup** [comment]
@TheAlphaNerd just bought a guitar (to finally replace my long-ago stolen one).

**Comment by TheAlphaNerd** [comment]
JAM TIME!

**Comment by rauchg** [comment]
@visnup my singing… well… I'd rather speak

**Comment by visnup** [comment]
@rauchg hahaha. You available 8/5? Any random topic you feel like talking about for 10 minutes?

**Comment by billyroh** [comment]
We've filled out all our karaoke slots! Thanks everyone! You can check them out on the site: http://wafflejs.com/
