### ISSUE TITLE
Add transition time to the schedule

### ISSUE THREAD

**Issue by makenai** [wafflejs/wafflejs.github.io#24]
I noticed that you have the schedule going from 7:40 to 7:50 and 10 minute long talks. There is always some slack time required for the previous speakers to get off of stage and the new speaker to get on and set up. I recommend adding at least 5 minutes between each event, especially if you're going to have the minute by minute schedule up on the site.

**Comment by kosamari** [comment]
@makenai at BrooklynJS we almost use this as joke for the event (our design is based on MTA subway which is always late, so as MTA we are also late on schedule) our event never ends at 8PM & talks actually start at 8PM :P
http://brooklynjs.com/

As organizer tho I do inform our speakers that schedule on the web is not accurate to the actual time.

**Comment by visnup** [comment]
added 5 minutes per
