### ISSUE TITLE
Call for Speakers: "June"

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#317]
We're looking for speakers for our meetup!

![](https://media.giphy.com/media/ItONzncuC9Z96/giphy.gif)

**How do I submit a talk?**
You can either comment on this issue or send us an email at talks@wafflejs.com.

**When and where will it be?**
When: Tuesday, May 29 from 7 to 10 PM.
Where: [Soma StrEat Food Park](https://www.google.com/maps/place/SoMa+StrEat+Food+Park/@37.769798,-122.412043,17z/data=!3m1!4b1!4m2!3m1!1s0x808f7e28b17fa279:0xcaa79b9fbbc34ee)

**What should I talk about?**
We don’t have a strict formula, but this is the balance we try to strike every month:
- **2x Creative Talks**: Creative applications of programming. Past examples are generating lego murals out of static images, and building an in-browser RPG.
- **1x Passion Talk**: Something you’re excited about outside of work. Past examples are starting and maintaining an open source project, and using meditation and programming side by side.
- **1x Technical Talk**: A deep dive on a technical topic. Past examples are optimizing your code for the V8 JavaScript engine, and using functional programming for developing UI.

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
We don’t have a strict formula for this either, but past successful submissions have included the following:

* What the audience should take away from the talk
* Why you’re excited about the subject
* A general outline of your talk (bullet points are good)

If you only have a rough idea, we’re also happy to workshop your idea with you in the #wafflejs channel on the [BoroJS Slack team](http://slack.borojs.com/).

**What's the A/V situation?**
We'll have a projector and a mic for you to use. Let us know if you need any fancy adapters (we'll have some Apple ones).

**Can I submit a talk for a thing I made, for either myself or my employer?**
Generally, no. We've found that when people give talks about a thing they made, it comes off as self-promotional. We'll make exceptions for this though, especially when it's less about the thing, but rather lessons learned by making the thing.

**Comment by dmvaldman** [comment]
I'd like to give a not-so-technical talk about a philosophical connection between "stateful" and "stateless" programming patterns. The title of the talk is "Descartes, Berkeley and Functional Reactive Programming". I gave it at BerlinJS a while back and would love to give a variant of it at WaffleJS! 

- What the audience should take away from the talk

A sense of belonging to a centuries old epistemological debate the next time they wrangle with inconsistent state in their codebases.

- Why you’re excited about the subject

Anytime I can relate philosophy to something practical I'm pretty excited.

- A general outline of your talk (bullet points are good)

I wrote a blog post about some of the comments that you can skim [here](https://medium.freecodecamp.org/descartes-berkeley-and-functional-reactive-programming-18b0b61eac58). I'll convert this into a 10-minute slide format.

**Comment by chromakode** [comment]
Thanks @dmvaldman, just sent you an email :+1:

**Comment by pranaygp** [comment]
I'd like to give a talk about a project I'm working on recently and something I think can make both an insightful and entertaining talk. My project lets people share keynote files (like the one I'll be making for WaffleJS) to a permalink that, when people visit, will be presented with a slideshow-in-the-browser experience. I plan to amke this presentation more about my experience building it than just the project itself.

* What the audience should take away from the talk

Learn about a new tool they can use to share presentations after a talk, but more importantly, experience a walk through of how I envisioned what I wanted to build and the somewhat humorous steps involved in building it out

* Why you’re excited about the subject

I often find little nice project I want to work on that require way more work than the resulting reward from working on it. At the same time, working on projects like that get me way more excitied about sharing them for the priceless expression on peoples faces when they realised how much time I'e wasted on the project 😛 

* A general outline of your talk (bullet points are good)

  * I wanted to share slides from my first talk but have a website people can just go to
  * First step - Realize that I could just do this easily, but I could instead extract parts of it out to make it look like I'm doing more work, and then open source each of those parts even though nobody will find them useful
  * Talk about the different parts of this in order with a few code samples empasizing the "over-architected" nature of it all
  * Build up to final tool (i.e. what I wanted to build in the first place)
  * Demo by using it on the slides from WaffleJS

**Comment by billyroh** [comment]
Thanks for submitting, everyone! Here's the CFP for July 👉  https://github.com/wafflejs/wafflejs.github.io/issues/350
