### ISSUE TITLE
Differentiate between speakers and singers

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#33]
Looking at the schedule, it's not clear who'll be speaking and who'll be doing karaoke. Let's fix that somehow!

**Comment by visnup** [comment]
true, the emoji's are oo-k, but not great at all.

**Comment by billyroh** [comment]
Yeah that's why I initially had :mega: for speakers and :microphone: for karaoke-ers. We should just label them though with text.

**Comment by visnup** [comment]
could also do left/right/left/right text alignment maybe too, like text conversation

**Comment by billyroh** [comment]
![image](https://cloud.githubusercontent.com/assets/748504/8609491/ba9b3328-265a-11e5-90e1-2b912f6cccf0.png)
an emoji timeline could be fun, but it feels a bit busy

**Comment by billyroh** [comment]
fixed here: https://github.com/wafflejs/wafflejs.github.io/pull/35
