### ISSUE TITLE
September Call for Speakers

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#34]
We're looking for speakers for our meetup!

![mind blown](https://media0.giphy.com/media/Fbyam9ZAJ3J1m/200.gif)

**How do I submit a talk?**
You can either comment on this issue or [send us an email](mailto:talks@wafflejs.com?subject=Talk Submission).

**When and where will it be?**
When: Wednesday, September 2 from 7 to 10 PM.
Where: [Soma StrEat Food Park](https://www.google.com/maps/place/SoMa+StrEat+Food+Park/@37.769798,-122.412043,17z/data=!3m1!4b1!4m2!3m1!1s0x808f7e28b17fa279:0xcaa79b9fbbc34ee)

**What should I talk about?**
Something you do outside of work. It doesn't have to be tech-related, but it'd be nice!

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
Just a few sentences describing what you want to talk about would be great.

**What's the A/V situation?**
We'll have a TV and a mic for you to use. Let us know if you need any fancy adapters (we'll have some Apple ones).

**Comment by coleww** [comment]
I'd like to present a talk about "Algorithmic Art".
This talk isn't necessarily about code art, but instead about works of art that follow an algorithm or process. Thus they can be created by either a computer or a human, but the computer will be able to do them much faster and at a larger scale than a human ever could. 

For example, an algorithmic poem: 
1. cut all the words out of a page of a magazine
2. put them in a hat
3. pull 5-7 words out at random and glue them onto a piece of paper

**Comment by notwaldorf** [comment]
I'd like to talk about emojis.

Last year, in the dark days of the web, Chrome couldn't render emojis. I tried to fix it, failed, and have been making silly emoji related [apps](https://github.com/notwaldorf/emoji-translate) ever since. 

And now I'm going to tell you about them!

**Comment by visnup** [comment]
@notwaldorf 😯

**Comment by notwaldorf** [comment]
@visnup oh noes, is that a good 😯or a bad 😯?

**Comment by visnup** [comment]
@notwaldorf haha, a good 😯. like a "oooh" 😯. I guess that's a problem with some of the emojis 😁.

**Comment by visnup** [comment]
@notwaldorf trivia: git, osx's terminal, and github handle emoji branch names well.

safari does an amazing job:
![screen shot 2015-07-15 at 2 05 46 pm](https://cloud.githubusercontent.com/assets/10444/8709897/9dcf4456-2afa-11e5-8b87-d51afe70fa31.png)

chrome is getting there:
![screen shot 2015-07-15 at 2 08 03 pm](https://cloud.githubusercontent.com/assets/10444/8709933/ebdf36d8-2afa-11e5-848f-5e2ea154dd0f.png)

**Comment by notwaldorf** [comment]
@visnup yeah, that's https://crbug.com/441946, the bane of my existence.

**Comment by billyroh** [comment]
@jeanieshark Still interested in speaking in September??

**Comment by justinelam** [comment]
I'd love to give a talk on Bookmarklets. They are pretty neat and powerful tools. I can teach how bookmarklets work, some examples of useful and fun bookmarklets, and I'll demo a table downloading bookmarklet that I created and then I’ll walk you through the 4 steps in creating your very own!

**Comment by s3ththompson** [comment]
If it fits with the overall vibe of the gathering, I'd be happy to give a very high-level explanation of the V8 JavaScript engine using GIFs or some other yet-to-be-determined, creative format.  Part of the talk would be the interesting details of how V8 takes dynamic JS and compiles it down to machine code on the fly.  The other part would be how developers can help the browser by writing code that's easy to make fast!

**Comment by billyroh** [comment]
Thanks for your submissions everyone! We've announced our speakers over here: http://wafflejs.com/

If you'd like to speak for our September event, we're accepting talks over here: https://github.com/wafflejs/wafflejs.github.io/issues/51
