### ISSUE TITLE
karaoke interludes

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#4]
ok, for the first meetup, I want to set the tone by doing live music accompaniment to js/tech people singing covers/karaoke. I have about a month to try to pull this off (going to also assume this public issue doesn't ruin the surprise since people don't have enough time to go rummaging around on github).

if anyone knows of people who'll be in town and want to rock the mic to sing their karaoke jam, let me know.

**Comment by hughsk** [comment]
Happy to do some live audio-reactive visuals, e.g. https://www.flickr.com/photos/toolmantim/sets/72157653507025562, if there's ever an event while I'm in town (next time is August/October I think?)

**Comment by visnup** [comment]
we're going to be shooting for monthly, so yes please definitely.

**Comment by visnup** [comment]
idea: find the one karaoke song a person is bomb-diggity at and do 5ish of those.

**Comment by hughsk** [comment]
Haha, excellent :)

**Comment by visnup** [comment]
closing in favor of #21
