### ISSUE TITLE
Talk Proposal: Managing the flow of asynchronous operations in Node.js

### ISSUE THREAD

**Issue by ErickWendel** [wafflejs/wafflejs.github.io#405]
## Managing the flow of asynchronous operations in Node.js

We know that Javascript flow's is different comparing with another languages, such a Java, Python and etc. When we make started  write async apps in Javascript some strange things happens, like a undefined values and unsynchronised results. This talk helps you to know how Javascript works and how synchronize resutls with Callbacks, Promises, Events and Reactive things in practice!

## About Erick Wendel
Independent Software Consultant, Microsoft MVP, instructor, speaker and Co-organizer at Nerdzao, Nerdgirlz, Javascript São Paulo and NodeBR Communities. Member of @hapijs node.js web framework. Post graduating in Business Intelligence with Big Data.  Microsoft Certified Professional and Microsoft Specialist in Web development technologies (focoused in Node.js and Typescript). 

Facebook: https://fb.com/page.erickwendel
Twitter: [https://twitter.com/erickwendel_](https://twitter.com/erickwendel_)

## Live coding:

Yes

## Audio:

no audio needed

**Comment by chromakode** [comment]
Thanks Erick, sent you an email!
