### ISSUE TITLE
Talk Proposal: Building Automated Robots to extract informations with Node.js and Typescript

### ISSUE THREAD

**Issue by ErickWendel** [wafflejs/wafflejs.github.io#406]
## Building Automated Robots to extract informations with Node.js and Typescript
In our lives, we make many repetitive actions, maybe to enter in web site to view data, register in a database, maybe to register a same item in some time or publish things on facebook repetitive times. In this talk, you can know the facilities to build your own robot, automated and ready to free your time, to focus only on is really important and strategic. We will know the Selenium Web Driver tool, to simulate a user on browser and to make all tasks "auto magically"
### Live coding:

Yes
### Audio:

no audio needed
## About Erick Wendel

Independent Software Consultant, Microsoft MVP, instructor, speaker and Co-organizer at Nerdzao, Nerdgirlz, Javascript São Paulo and NodeBR Communities. Member of @hapijs node.js web framework. Post graduating in Business Intelligence with Big Data. Microsoft Certified Professional and Microsoft Specialist in Web development technologies (focoused in Node.js and Typescript).

Facebook: https://fb.com/page.erickwendel
Twitter: [https://twitter.com/erickwendel_](https://twitter.com/erickwendel_)
Github: [https://github.com/erickwendel](https://github.com/erickwendel)

**Comment by chromakode** [comment]
Thanks Erick, sent you an email!
