### ISSUE TITLE
September Call for Performers

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#45]
We're looking for people to perform at our meetup!

![I just wanna sing](http://38.media.tumblr.com/fc4adc9b136fda5aec00c4bbcb3e6775/tumblr_mysco2zJSc1qec814o1_500.gif)

**What kind of performance are you looking for?**
It can be karaoke, plate-spinning, or fire-eating. Basically anything you want. If you're into, we're into it.

**How do I submit a performance?**
You can either comment on this issue or [send us an email](mailto:karaoke@wafflejs.com?subject=Performance Submission).

**How long should my performance be?**
It should be <6 min long, so no Hotel California please!

**Do I need to be a good singer?**
Nope. You just need to be enthusiastic and [give us LIFE](https://ioneglobalgrind.files.wordpress.com/2014/05/yasss.gif?w=771&h=435).

**What should be in my submission?**
A description of what you'll be performing and what kind of equipment you'll need.

**Comment by TheAlphaNerd** [comment]
can I play some music?

**Comment by TheAlphaNerd** [comment]
Oops... I'll be in the desert on the 2nd

**Comment by visnup** [comment]
We have Natasha lined up for next month.

**Comment by ggilder** [comment]
I'd love to play a song or two. Will there be any gear there, like say a piano? I can also bring a keyboard.

**Comment by visnup** [comment]
Natasha is actually bringing a keyboard. Let me get specifics.

**Comment by visnup** [comment]
@ggilder you can use Natasha's keyboard but she says it'll be art-ed up so as long as you don't mind that.

**Comment by ggilder** [comment]
lol... I don't know quite what to expect but I'll roll with it. :musical_keyboard: :sparkles: :art:

**Comment by billyroh** [comment]
@ggilder Great! We just added you to [the lineup](http://wafflejs.com/). You may want to bring a keyboard just in case the other one doesn't work out :smile: :musical_keyboard: 

Do you know what kind of song you'll be singing?

**Comment by billyroh** [comment]
Also, do you have a short bio for yourself? We'd like to introduce you before you go on stage

**Comment by ggilder** [comment]
Sounds good, I'll stop by whenever you're getting set up (6:30?) to check out Natasha's setup. I'll have a keyboard nearby at my office that I can bring over if that doesn't work out but it'll probably be fine. :smile: 

I'll probably be singing either a wistful cowboy song or a song based on Abraham Lincoln's first inaugural address. Uh... not sure if that's what you wanted to know. :wink:

How's this for a bio?

> Gabriel Gilder is a developer at Square, where he curses databases and tries to pretend that JavaScript doesn't exist. He performs psychedelic Americana rock'n'roll with his band SUPERVAGUE. And he is always down for karaoke.

**Comment by visnup** [comment]
closing for #54.
