### ISSUE TITLE
Sponsorship Package

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#50]
**What's WaffleJS?**
It's a monthly meetup with tech, waffles, and karaoke. We host four ten-minute talks and have open karaoke at the end. [Learn more](http://wafflejs.com/).

**How much?**
$500.

**Who else has sponsored so far?**
[Opendoor](https://www.opendoor.com), [Particle](https://www.particle.io/), and [Crunchyroll](https://www.crunchyroll.com).

**How many sessions have you had?**
Our first session was in August 2015 and we meet monthly. See our past events here: [August](https://wafflejs.com/past/2015-08), [September](https://wafflejs.com/past/2015-09)

**How many attendees are there?**
The October session will have around 150 people. Past attendees have been developers from established companies (Google, Square, Dropbox) as well as folks from smaller startups.

**What do I get?**
* A minute of stage time to pitch your company. (May we suggest haikus, interpretive dancing, or freestyle underwater basketweaving?)
* 2 tickets for people at your company.
* Place to put stickers and swag on the check-in desk.
* Featured in the emails to the attendees.
* Shown on [wafflejs.com](http://wafflejs.com/).

**Where does the money go?**
The money covers the cost of the venue, labour, and equipment. Any profit we make will be donated to [Girls Who Code](http://girlswhocode.com/).

**How can I participate?**
Send us a message at sponsors@wafflejs.com.

**Comment by visnup** [comment]
done with the [new sponsorship page](https://wafflejs.com/sponsorship)?

**Comment by billyroh** [comment]
Yarp. Feel free to close.
