### ISSUE TITLE
October Call for Speakers

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#51]
We're looking for speakers for our meetup!

![knowledge](https://media.giphy.com/media/OQsa4Yca9BJFS/giphy.gif)

**How do I submit a talk?**
You can either comment on this issue or [send us an email](mailto:talks@wafflejs.com?subject=Talk Submission).

**When and where will it be?**
When: Wednesday, October 7 from 7 to 10 PM.
Where: [Soma StrEat Food Park](https://www.google.com/maps/place/SoMa+StrEat+Food+Park/@37.769798,-122.412043,17z/data=!3m1!4b1!4m2!3m1!1s0x808f7e28b17fa279:0xcaa79b9fbbc34ee)

**What should I talk about?**
Something you're excited about, outside of work. It doesn't have to be tech-related, but it'd be nice!

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
Just a few sentences describing what you want to talk about would be great.

**What's the A/V situation?**
We'll have a projector and a mic for you to use. Let us know if you need any fancy adapters (we'll have some Apple ones).

**Comment by jskulski** [comment]
Hi! 

I'd like to talk about improvisation and software engineering, specifically how they are both group creative works, and I'll probably center the talk around body language. That's weird!

Thanks!

**Comment by visnup** [comment]
> That's weird!

😁

**Comment by visnup** [comment]
@bengotow hi! any interest in giving a talk at WaffleJS in October?

**Comment by jkup** [comment]
I'd love to speak on Chrome developer tools pro-tips. I made a small video the other day https://www.youtube.com/watch?v=0eSAsi3GPh4 - my talk could be a condensed version plus some extra tips

**Comment by julianguyen** [comment]
Hey everyone! 

I'd love to speak about my open-source mental health project if me (http://github.com/julianguyen/ifme). Specifically, I want to talk about my first-time experiences leading an OSS project, managing/engaging diverse contributors, technical lessons I've learned along the way (with regard to RoR, JS, testing automation).

Thanks!

**Comment by davidkpiano** [comment]
I've got a talk idea!

"Sassy JavaScript" - With Node-Sass, JavaScript and Sass can now play nicely with each other. I'll briefly talk about how you can actually share JS objects, functions, and more in your Sass projects, the awesome things you can do with that, and introduce the open-source project I've written to do just that: https://github.com/davidkpiano/sassport

Let me know what you think!

**Comment by s3ththompson** [comment]
Copying this over from the last thread:
If it fits with the overall vibe of the gathering, I'd be happy to give a very high-level explanation of the V8 JavaScript engine using GIFs or some other yet-to-be-determined, creative format. Part of the talk would be the interesting details of how V8 takes dynamic JS and compiles it down to machine code on the fly. The other part would be how developers can help the browser by writing code that's easy to make fast!

**Comment by billyroh** [comment]
Thanks for your submissions everyone! We've announced our speakers over here: http://wafflejs.com. For submitting your talks, I've sent you all free tickets :mailbox: 

If you'd like to speak for our September event, we're accepting talks over here: https://github.com/wafflejs/wafflejs.github.io/issues/64
