### ISSUE TITLE
Investigate cheaper ti.to pricing

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#52]
Currently 3% up to €10. Can pay a yearly fee for cheaper rates. This is all on top of Stripe pricing.

![screen shot 2015-08-27 at 3 25 01 pm](https://cloud.githubusercontent.com/assets/10444/9534751/d84ab880-4ccf-11e5-907d-47717464fe8c.png)

**Comment by billyroh** [comment]
that 3% is brutal. i'm guessing it's a lot of work to do our own ticketing thing, right?

**Comment by visnup** [comment]
I'm guessing the Basic plan will save us money, but need to do the calculation.

**Comment by visnup** [comment]
er, 1% of August is $6.68. 49 EUR = $55.70 / 12 = $4.64/month. so, we'd save $2/mo. :stuck_out_tongue:

**Comment by visnup** [comment]
the larger processing fees are actually Stripe at 2.9% + $0.30. effectively 5.9% to Stripe.

**Comment by billyroh** [comment]
Eventbrite is 5.5% + $0.99 per transaction, so I think it's cheaper: http://help.eventbrite.com/customer/en_us/portal/articles/1809983

**Comment by visnup** [comment]
that's 15.5% total. right now we're at 8.9% (based on a $10 ticket).

**Comment by visnup** [comment]
if we're a savvy merchant, we'd have people buy "ticket packs" of 10 tickets or whatever good for whenever, minimizing that $0.30 fee from stripe.

**Comment by TheAlphaNerd** [comment]
Have you considered writing Paul from Tito to see if you can work something out? They are pretty approachable and respond quickly to tickets

**Comment by visnup** [comment]
actually, now that we're gearing up to sell more tickets this will save us more...

**Comment by visnup** [comment]
the Basic plan will now save us $12.77 per month with the projected ticket revenue for October. costs for stripe also will go down on a percentage basis for October, just because of a slightly larger per ticket price.

I think we should really think about doing some sort of ticket pack thing to save some of the ~$100 going to stripe.

**Comment by visnup** [comment]
it would also mean more likely recurring attendees.

**Comment by billyroh** [comment]
i think we're making enough money where the fees don't mean much anymore
