### ISSUE TITLE
October Call for Performers

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#54]
We're looking for people to perform at our meetup!

![I just wanna sing](https://media4.giphy.com/media/ehC0HERKWX5M4/200.gif)

**What kind of performance are you looking for?**
It can be karaoke, plate-spinning, or fire-eating. Basically anything you want. If you're into, we're into it.

**How do I submit a performance?**
You can either comment on this issue or [send us an email](mailto:karaoke@wafflejs.com?subject=Performance Submission).

**How long should my performance be?**
It should be <6 min long, so no Hotel California please!

**Do I need to be a good singer?**
Nope. You just need to be enthusiastic and [give us LIFE](https://ioneglobalgrind.files.wordpress.com/2014/05/yasss.gif?w=771&h=435).

**What should be in my submission?**
A description of what you'll be performing and what kind of equipment you'll need.

**Comment by coleww** [comment]
![screen shot 2015-09-07 at 6 32 01 am](https://cloud.githubusercontent.com/assets/5067315/9722736/e4be8eb6-5567-11e5-86ca-22816527903c.png) 

I offer unto the waffle gods a presentation/demonstration of karaoke_ebooks: give it a twitter username and it will pull down a bunch of that users tweets and apply some markov chains and other language-processing magic to construct rhymes into a "song", and then display those lyrics in karaoke style over some probabilistically generated web audio beats. 

https://twitter.com/horse_js would be the most obvious target for a waffle performance i think...

**Comment by TheAlphaNerd** [comment]
I'd love to do a musical performance with my monome!

**Comment by visnup** [comment]
@TheAlphaNerd you were on my list of people to reach out to! that could be pretty cool.

**Comment by TheAlphaNerd** [comment]
Woot!

If you want to do a music performance theme I can help co-ordinate others

**Comment by visnup** [comment]
@coleww whoa, fancy.

**Comment by visnup** [comment]
@TheAlphaNerd do you happen to have any samples or video anywhere of what you want to do?

**Comment by coleww** [comment]
@visnup i pushed the thing live if you wanna check it out: http://www.karaoke-ebooks.party/

**Comment by visnup** [comment]
@coleww ok now I want to use this for something
