### ISSUE TITLE
Slack invite link no longer active

### ISSUE THREAD

**Issue by courier-new** [wafflejs/wafflejs.github.io#570]
Hey there!

Not sure where the right place to raise this issue this, but it seems the slack invite link is no longer active:

![image](https://user-images.githubusercontent.com/8942601/67705972-3956f200-f975-11e9-847d-c25c6ea558ab.png)

I tried sending a DM over twitter, as well, but figured the visibility on GitHub wouldn't hurt. If this isn't the right place to point this out, please feel free to close!

**Comment by visnup** [comment]
hrmmmmm this is via slackin? you get an invite link, but then it's expired?

**Comment by courier-new** [comment]
Ah, no, sorry, this is in reference to the shared invite direct link from the website:
https://github.com/wafflejs/wafflejs.github.io/blob/master/routes/index/index.jade#L181

**Comment by andytuba** [comment]
We're still working on getting a new invite link.

In the meanwhile, please send your email in a comment here and mention @andytuba, or send your email in a DM to 🐦 [@wafflejs](https://twitter.com/wafflejs).

**Comment by andytuba** [comment]
Also, let's update the **several** "join us on Slack" links to "DM twitter.com/WaffleJS with your email to request an invite".  (Feel free to submit a PR, yall!)

**Comment by shivaylamba** [comment]
@andytuba The slack link still doesnt work

**Comment by andytuba** [comment]
We've migrated to Discord: https://discord.com/invite/mq3k5Jh

(yes, that needs updated on the site)

**Comment by chromakode** [comment]
I've updated the site to link to the Discord instead of Slack. Thanks for bumping this!
