### ISSUE TITLE
Call for Speakers: January 2020

### ISSUE THREAD

**Issue by andytuba** [wafflejs/wafflejs.github.io#572]
We're looking for speakers for our meetup!

![](https://media.giphy.com/media/XxMTS8OOwl59C/giphy.gif)

**How do I submit a talk?**
You can either comment on this issue or send us an email at talks@wafflejs.com.

**When and where will it be?**
When: Wednesday, December 8 from 7 to 10 PM.
Where: [Soma StrEat Food Park](https://www.google.com/maps/place/SoMa+StrEat+Food+Park/@37.769798,-122.412043,17z/data=!3m1!4b1!4m2!3m1!1s0x808f7e28b17fa279:0xcaa79b9fbbc34ee)

**What should I talk about?**
We don’t have a strict formula, but this is the balance we try to strike every month:
- **2x Creative Talks**: Creative applications of programming. Past examples are generating lego murals out of static images, and building an in-browser RPG.
- **1x Passion Talk**: Something you’re excited about outside of work. Past examples are starting and maintaining an open source project, and using meditation and programming side by side.
- **1x Technical Talk**: A deep dive on a technical topic. Past examples are optimizing your code for the V8 JavaScript engine, and using functional programming for developing UI.

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
We don’t have a strict formula for this either, but past successful submissions have included the following:

* What the audience should take away from the talk
* Why you’re excited about the subject
* A general outline of your talk (bullet points are good)

If you only have a rough idea, we’re also happy to workshop your idea with you on our [Slack channel](https://borojs.slack.com/join/shared_invite/enQtMzM2Nzc5ODExNjY2LTUyNTg3OGMzMzhhNWU2OWViNWUxNmMyZjA5NmMzNGFhYmJkOWE5NzA4NWI5ZGY2NjdmNzBmYWJjMjYzZjkwOGE)  (#wafflejs).

**Do I have to buy a ticket if I get selected?**
Nope! You'll get a free ticket.

**What's the A/V situation?**
We'll have a projector and a mic for you to use. Let us know if you need any fancy adapters (we'll have some Apple ones).

**Can I submit a talk for a thing I made, for either myself or my employer?**
Generally, no. We've found that when people give talks about a thing they made, it comes off as self-promotional. We'll make exceptions for this though, especially when it's less about the thing, but rather lessons learned by making the thing.

**Comment by FredKSchott** [comment]
Now that its been [announced publicly](https://twitter.com/pikapkg/status/1196825435671158787), I'd love to share what we're doing at http://pika.dev/. I'll unfortunately be traveling during the December meetup but could do January.

**Comment by maxedmands** [comment]
Hi! I have a 10m talk about something I’m particularly excited about: **feedback loops**! Here’s my pitch.

### takeaways:
- feedback loops give you incremental information about whatever thing you’re doing, so you can do that thing more effectively
- the best feedback is high-bandwidth, timely, and relevant
- the best feedback loops are tight and integrated right into your workflow
- it is smart to be continuously aware of the incredibly rich contextual information you have right in front of you

### why I’m excited:
- they are applicable to literally anything you do in tech
- noticing them is a mindset, and when you start noticing them they show up everywhere

### outline
- what is a feedback loop
- some examples
- how to notice / take advantage of them

**Comment by tmcw** [comment]
Hello! I'd love to do a 10-minute talk on **How math keeps changing**.

## What the audience should take away from the talk

- Even at the most basic level of programming, our abstractions are still just that - abstractions - and have awkward mismatches with human or mathematical expectations.
- This issue - that basic trigonometry changes between versions - has real-world ramifications.
- The basic level of math is usually estimated, and sometimes calculated in ways that we'd never expect.
- The idea that basic abstractions are neither consistent nor always even correct is general to programming
- A few solutions _do_ exist, like stdlib

## Why I'm excited

- This is a universal problem that doesn't get enough airtime
- It's funny, in the way that the folly of modeling the world in bits and bytes can be funny
- It's super deep but can be explained in a way that's accessible to everyone

## Outline

- How basic math problems have surfaced in real world applications like simple-statistics and mapbox-gl
- Discovering that the JavaScript spec doesn't define trigonometry
- Why wouldn't it define trigonometry?
- How does trig actually work, at the lowest and middle levels?
- Galaxy-brain take on speed vs consistency, on the challenge of extremely heterogenous environments (different chips, computers, browsers, OSes), and context with other languages

**Comment by chromakode** [comment]
Hey @maxedmands and @tmcw, thanks for these pitches! We're currently reviewing and will be in touch via email shortly. :smile:
