### ISSUE TITLE
Processify our talk selection process

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#62]
We end up selecting talks based on consensus of the organizers after going through all the proposals we've seen either on GitHub or email for the current months and past months. Our current process is haphazard at best. It's also likely unclear what the selection process is from the outside since there barely is a process on the inside.

We should figure out a better process and if not democratize it, at least publicize it. It should address:

- take into account all proposals, new and old
- leave some control to the organizers to help guide the meetup
- don't let proposals fall through the cracks
- give constructive feedback to the proposer
- allow transparency(?), balancing the privacy of the proposals we get via email

This is meant as a discussion topic more than a solution right now.

**Comment by nebrius** [comment]
Another thing to consider when balancing out transparency vs privacy is the "embarrassment factor." Not being selected for a talk can be rather heartbreaking...having that rejection, much less the reasons why, being broadcast to the world would be much more traumatizing and could negatively impact submissions over time.

For me, personally, I've never cared to know why proposals I was competing against were or were not selected for meetups/conferences I've submitted too. I've only wanted to know whether or not my talk was selected, and _maybe_ a brief explanation of why it was rejected.

I don't think that transparency is a valuable end unto itself, it's important to ask why and how transparency will improve things.

**Comment by visnup** [comment]
@nebrius good points. no one has actually asked this of us, but internally I (we?) were feeling guilty and thinking "I hope no one is going to wonder how/why we make these decisions". we're also not that great at getting back to every single person with a flat-out rejection either[1].

I guess if anything, before proposing a talk, some people would benefit from a clear explanation of how it'll be evaluated against others so they know how best to pitch one.

[1]: I never see our "no"s as being no's to the speaker. we try to keep every proposal/proposer around so even if the last proposal they sent just isn't resonating with us, we can go back to them and ask for a different idea later. I like how with this format we get 4 slots every month.

**Comment by nebrius** [comment]
> I guess if anything, before proposing a talk, some people would benefit from a clear explanation of how it'll be evaluated against others so they know how best to pitch one.

+1 This would be very helpful!

> I never see our "no"s as being no's to the speaker. we try to keep every proposal/proposer around so even if the last proposal they sent just isn't resonating with us, we can go back to them and ask for a different idea later. I like how with this format we get 4 slots every month.

Maybe you could send out a "your talk wasn't selected this time, but we still love you and want to keep you in mind for future events" like email?

**Comment by visnup** [comment]
I've noticed the distribution of topics we've fallen into, which I wanted to document somewhere, is:

- 2x creative/design/js talks
- 1x passion talk
- 1x highly technical talk

I'm liking that mix personally too.

**Comment by nebrius** [comment]
+1 on the mix of talks, I agree it's a good blend. Maybe this could be useful info to put in the call for speakers, to help authors with proposals?

**Comment by visnup** [comment]
we have wafflejs.com/speakers now to try to guide speakers a bit more.

**Comment by nebrius** [comment]
👌 Nice, I like it. Lays out the process and expectations quite well.

**Comment by visnup** [comment]
going ahead and closing this for now then. @nebrius thanks for your input!
