### ISSUE TITLE
November Call for Speakers

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#64]
We're looking for speakers for our meetup!

![knowledge](https://media.giphy.com/media/bsyc2LUo9ToWY/giphy.gif)

**How do I submit a talk?**
You can either comment on this issue or [send us an email](mailto:talks@wafflejs.com?subject=Talk Submission).

**When and where will it be?**
When: Wednesday, November 4 from 7 to 10 PM.
Where: [Soma StrEat Food Park](https://www.google.com/maps/place/SoMa+StrEat+Food+Park/@37.769798,-122.412043,17z/data=!3m1!4b1!4m2!3m1!1s0x808f7e28b17fa279:0xcaa79b9fbbc34ee)

**What should I talk about?**
Something you're excited about, outside of work. It doesn't have to be tech-related, but it'd be nice!

**Do I need to be an expert to talk?**
Nope. This meetup is supposed to be fun and casual, so we want everyone to participate. We especially encourage people of underrepresented groups to apply.

**How long should my talk be?**
Ten minutes. There won't be any formal Q&A.

**What should be in my talk submission?**
Just a few sentences describing what you want to talk about would be great.

**What's the A/V situation?**
We'll have a projector and a mic for you to use. Let us know if you need any fancy adapters (we'll have some Apple ones).

**Comment by kosamari** [comment]
![z 2](https://cloud.githubusercontent.com/assets/4581495/10675244/24917656-78cd-11e5-92a8-9b2bc3b9bd41.jpg)

I want to talk about basic of image processing (gray scaling, edge detection, blur, photo filter) 
let's look at what "a Pixel" is & how you can manipulate for fun with Canvas API & JavaScript.
