### ISSUE TITLE
Create sponsorship documentation

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#66]
* In web and pdf form
* Show photos of recent meetups
* Talk about how it contributes to the community
* Show past speakers

**Comment by visnup** [comment]
attendance numbers, very high-level an idea of what companies attendees are from (balanced with privacy), or anything else so a sponsor can get an idea for what "community" this meetup is in.

**Comment by visnup** [comment]
or, from a sponsor's perspective, I think what they're trying to answer in making the sponsorship decision:

- what's my ROI (for recruiting or brand-recognition or product adoption)?
  - what's the volume of attendees
  - what's the quality of attendees
    - are they in my target market

**Comment by billyroh** [comment]
Here's Cascadia's for reference: http://cl.ly/3W3i2f41183Q/sponsor-brochure%20(1).pdf

**Comment by visnup** [comment]
New page at wafflejs.com/sponsorship
