### ISSUE TITLE
emcee, a master of ceremonies

### ISSUE THREAD

**Issue by visnup** [wafflejs/wafflejs.github.io#7]
I'm willing to give the hosting a shot, but I'm no @jed nor @brianloveswords. anyone know of a similar personality in the bay area?? this is a dangerous issue as it could be a touchy subject if I personally veto someone here... but, if @maxogden were still in town, I'd love his style. @isaacs is on my short list, but you know, time commitments.

**Comment by isaacs** [comment]
Yeah, the time commit is tough for me.  Some other possible JS emcee's that spring to mind: @mikeal @rockbot @brianleroux @ceejbot

**Comment by visnup** [comment]
@emilyrose is going to be co-organizing and would be a wonderful host too.

**Comment by brianleroux** [comment]
waffles, eh 

enjoy doing the mc thing and happy to help / when is this? I can also bring syrup.

**Comment by mikeal** [comment]
ProTip: Don't try to organize the event *and* MC, it's actually a lot of work and prep to be a great MC so it's best to delegate it.

**Comment by mikeal** [comment]
ProTip #2: Mikeal is not a great MC.

**Comment by jed** [comment]
it is a lot of work to be sure, but in the early stages of an event i think
it's really helpful to help set the tone and gel the culture.

**Comment by kosamari** [comment]
To @mikeal 's ProTip 1. BrooklynJS was happy coincidence that Jed was detail oriented organizer + Jed and Brian were seriously good Emcees.
I know its alot of work to do both & I am happy that I can at least help the organizing part now. 

I still like that BrooklynJS emcees are part of organizing team not like someone we borrowed for the night. (We all care about who we select for talks & what goes into the meetup.) It definitely sets the tone.

**Comment by llkats** [comment]
+1 to @brianleroux :grinning: :grinning: :grinning:

**Comment by visnup** [comment]
yeah, tone-setting-wise I'm already gearing up to practice my ukulele non-stop for the next month in order to pull out an opening diddy.

**Comment by visnup** [comment]
going to be me and @emilyrose. :crossing_fingers:

**Comment by visnup** [comment]
@brianleroux going to be August 5 at SOMA Streat food now. if we bomb at MCing, I'm going to hit you up for next time :)

**Comment by brianleroux** [comment]
hahah it'll rawk I'm sure :heart: :shipit:
