### ISSUE TITLE
Merge w/ Evening of JS

### ISSUE THREAD

**Issue by mikeal** [wafflejs/wafflejs.github.io#9]
I came up with a bunch of crazy ideas for https://github.com/mikeal/An-Evening-Of-JS but didn't quite get it off the ground.

We should bring over some of the ideas and ditch the name (WaffleJS is a much better name).

**Comment by visnup** [comment]
I'm all for the merge in. know of a tool to do it? hand transcribe some? cross-ref? just ask github support? 😁

**Comment by mikeal** [comment]
I'll just pull over some of the issues that I think need to come over.

**Comment by visnup** [comment]
@mikeal will leave this up to you
