### ISSUE TITLE
Speaker Brunch Proposal

### ISSUE THREAD

**Issue by billyroh** [wafflejs/wafflejs.github.io#99]
#### What's this?
We'd like to thank our speakers, performers, and our sponsors by buying them brunch. This is a chance for everyone to hang out and socialize. And of course, we'd welcome any feedback you have for us along the way.

#### When and where?
**Date & Time:** Sunday, January 31 at 1pm
**Location:** Visnu's Place (Dogpatch, SF)
**Format:** Catered brunch buffet from Hard Knox Cafe

#### Who's invited?
* Speakers and performers from October, November, December, January
* Co-organizers (Visnu, Billy, Kelly, Emily)
* Two engineers from each sponsor (New Relic, Opendoor, Dropbox)
* +1s of people attending

#### How frequent will this be?
Every three months. We'll invite speakers and sponsors from that month and the preceding two months.

-----

#### Checklist
* [x] Create site
* [x] Tito: https://ti.to/wafflejs/brunch
* [x] Send link to Mariko, Raquel, Shirley, Victor (@visnup)
* [x] Send link to Jon, Georgia, Melinda (@kellyk)
* [x] Send link to Alex (@thealphanerd)
* [x] Send link to the rest of speakers, performers (@billyroh)
* [x] Send link to sponsors (@billyroh)
* [x] Get final headcount
* [x] Put in order at Hard Knox Cafe
* [ ] Send reminder email

**Comment by visnup** [comment]
Success! 🍳 was a success. Let's do this again.
